### ISSUE TITLE
Rebuilt rom not passing 1+ logo

### ISSUE THREAD

**Issue by wertus33333** [omnirom/android_device_oneplus_oneplus2#2]
Rebuilding Omni 7.1 with official omni device tree and kernel (tried multiple vendors and also extracted from older omni build) results in the device hanging at the 1+ logo. Probably a kernel problem (working with newest boeffla, but no idea which commit is causing it).

**Comment by wertus33333** [comment]
guess noone will fix this

**Comment by Entropy512** [comment]
This is not the proper place to report issues, use Jira.

**Comment by wertus33333** [comment]
Thanks for the hint. Nougat is however, "old" and my build is working so i think i'll let this rest in peace here ;).
